In [2]:
import torch
import torch.version
torch.version

<module 'torch.version' from '/home/devs/anaconda3/lib/python3.11/site-packages/torch/version.py'>

In [3]:
torch.__version__

'2.0.1'

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [7]:
scalar.item()  #its used to retrive the number which work as python integer

7

In [9]:
vector = torch.tensor([7,7])  #vector
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.dtype

torch.int64

In [12]:
vector.shape

torch.Size([2])

In [13]:
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.shape

torch.Size([2, 2])

In [15]:
matrix.ndim

2

In [16]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
tensor.ndim

3

In [18]:
tensor.shape

torch.Size([1, 3, 3])

In [22]:
#create the tensor with random number
tensor = torch.rand(size=(3,4))
tensor, tensor.dtype, tensor.ndim

(tensor([[0.1250, 0.3794, 0.4841, 0.0733],
         [0.7095, 0.5290, 0.2494, 0.5626],
         [0.0215, 0.6639, 0.6364, 0.7665]]),
 torch.float32,
 2)

In [23]:
tensor = torch.rand(size=(224,224,3))
tensor.ndim

3

In [24]:
tensor.shape

torch.Size([224, 224, 3])

In [25]:
#create the tensor with zero , its useful for masking so model not learn anything about that tensor
zerotensor = torch.zeros(size=(3,4))
zerotensor.ndim, zerotensor.dtype

(2, torch.float32)

In [26]:
zerotensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
#create tensor with ones only
onetensor = torch.ones(size=(3,4))
onetensor, onetensor.shape, onetensor.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([3, 4]),
 torch.float32)

In [28]:
#create tensor for range
tensorrange = torch.arange(0,10,1)  #python used range for for creating range for numbers
tensorrange


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
tensorzerolike = torch.zeros_like(input=tensorrange)
tensorzerolike, tensorzerolike.shape

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([10]))

In [32]:
#there are different datatype in pytorch for tensor like float 32 is most common and float64 that is high precision, and we also have 8bit , 16bit and 32bit and 64bit integer values
tensor = torch.tensor([3,4,5],dtype=None, device=None, requires_grad=False)
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3]), torch.int64, device(type='cpu'))

In [34]:
tensor = torch.tensor([3.0, 4.0, 5.0], dtype=torch.float16)
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3]), torch.float16, device(type='cpu'))

In [35]:
#most common artibute for retrive information from the tensor is shape, dtype and device
sometensor = torch.rand(3,4)
print(f"shape of the tensor : {sometensor.shape}")
print(f"type of the tensor:{sometensor.dtype}")
print(f"where the tensor is store:{sometensor.device}")



shape of the tensor : torch.Size([3, 4])
type of the tensor:torch.float32
where the tensor is store:cpu


In [36]:
#tensor menupulation operation like addition , substraction , multipication (elementwise), division and matrix multipication
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [38]:
tensor*100   # value inside the tensor doesnt change unless we reassign them to another variable

tensor([100, 200, 300])

In [39]:
#reassign tensor
tensor = tensor-10

In [40]:
tensor

tensor([-9, -8, -7])

In [41]:
tensor = tensor+10

In [42]:
tensor 

tensor([1, 2, 3])

In [43]:
torch.multiply(tensor, 100)

tensor([100, 200, 300])

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [46]:
tensor

tensor([1, 2, 3])

In [47]:
print(tensor ,"*", tensor)
print("equal:", tensor*tensor)  # that give the element wise multipication in tensors

tensor([1, 2, 3]) * tensor([1, 2, 3])
equal: tensor([1, 4, 9])


In [48]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [49]:
tensor

tensor([1, 2, 3])

In [50]:
tensor*tensor   # elementwise maltiplication

tensor([1, 4, 9])

In [51]:
torch.matmul(tensor, tensor) # matrix maltiplication

tensor(14)

In [52]:
tensorA = torch.tensor([[1,2],[3,4],[5,6]])
tensorB = torch.tensor([[7,8],[9,10],[11,12]])

In [53]:
torch.matmul(tensorA, tensorB)  # we are getting error for such opertion beacuse inner shape is unmatch in this case. so this is most common error in pytorch 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [54]:
torch.matmul(tensorA, tensorB.T)   #this work because here we change the inner shape and outer shape is the output of the operation

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [64]:
tensorA = torch.tensor([[1,2],[3,4],[5,6]], dtype=torch.float32)
tensorA.shape, tensorA.dtype

(torch.Size([3, 2]), torch.float32)

In [66]:
#matrix multiplication in neural network
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features= 6)
output = linear(tensorA)
print(f"the shape of input : {tensorA.shape}")
print(f"the shape of output : {output.shape}")

the shape of input : torch.Size([3, 2])
the shape of output : torch.Size([3, 6])


In [67]:
#now we want to change the infeature dim from 2 to 3 so making this working we have to change the dimension of input different
torch.manual_seed(42)
linear=torch.nn.Linear(in_features=3, out_features=6)
x = tensorA
output= linear(x.T)
print(f"the shape of input x : {x.shape}")
print(f"the shape of the output: {output.shape}")

the shape of input x : torch.Size([3, 2])
the shape of the output: torch.Size([2, 6])


In [68]:
#agrregation of tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [69]:
x.dtype

torch.int64

In [70]:
print(f"the min value of x {x.min()}")
print(f"the max value of x {x.max()}")
print(f"the sum of x {x.sum()}")
print(f"the mean value of x {x.type(torch.float32).mean()}")

the min value of x 1
the max value of x 91
the sum of x 460
the mean value of x 46.0


In [71]:
# the same we can done with torch module
torch.min(x), torch.max(x), torch.sum(x), torch.mean(x.type(dtype=torch.float32))

(tensor(1), tensor(91), tensor(460), tensor(46.))

In [73]:
#find the position of min and max value in tensor . its really helpful during the softmax activation
tensor = torch.arange(10,100,10)
print(f"the value of the tensor : {tensor}")
print(f"position of the min value of the tensor {torch.argmin(tensor)}")
print(f"the position of max value {torch.argmax(tensor)}")

the value of the tensor : tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
position of the min value of the tensor 0
the position of max value 8


In [74]:
#common error in pytorch is datatype so pytorch always work with same dtype
tensor = torch.arange(10., 100., 10)
tensor.dtype

torch.float32

In [76]:
tensorfloat16 = tensor.type(torch.float16)
tensorfloat16.dtype

torch.float16

In [77]:
tensorint8 = tensor.type(torch.int8)
tensorint8.dtype

torch.int8

In [78]:
# changing the shape of tensor (there are many way for that one is reshape method , view method , stack- add the tensor in stack, squazee its remove extra dimesion from tensor and unsqueze add the extra dimension in  the tensor)
# permute method change the shape position of the tensor

tensorA = torch.arange(1,10)
tensorA

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
tensorA.shape

torch.Size([9])

In [81]:
#reshape the tensor
tensor = tensorA.reshape(1,9)
tensor.shape
tensor

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [83]:
# view the tensor in different way
tensor = tensorA.view(1,9)
tensor

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [84]:
tensor[:,0]=5
tensor

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [85]:
tensorA # view have change the original view in the tensor

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
#stack the tensor in the tensor along the dim=0 which is known as along the row
tensor = torch.stack([tensorA, tensorA, tensorA, tensorA, tensorA], dim=0)
tensor

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [89]:
tensor.shape

torch.Size([5, 9])

In [90]:
tensor = torch.squeeze(tensor, dim=0)
tensor

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [91]:
tensor.shape

torch.Size([5, 9])

In [92]:
tensorA.shape

torch.Size([9])

In [93]:
tensor = tensorA.reshape(1,9)

In [94]:
tensor.shape

torch.Size([1, 9])

In [95]:
tensor

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [96]:
tensor = torch.squeeze(tensor, dim=0)
tensor.shape

torch.Size([9])

In [97]:
tensor = torch.unsqueeze(tensor, dim=0)

In [98]:
tensor.shape

torch.Size([1, 9])

In [99]:
tensor = torch.rand(224,224,3)
tensor.shape

torch.Size([224, 224, 3])

In [101]:
tensor = torch.permute(tensor, dims=(2,1,0))
tensor.shape

torch.Size([3, 224, 224])

In [102]:
#indexing in the pytorch is very similar to python and we have indexing from outer dim to inner dimension
tensor = torch.arange(1,10).reshape(1,3,3)
tensor.shape

torch.Size([1, 3, 3])

In [103]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [104]:
tensor[0]  # this give the first channel of the given tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [105]:
tensor[0][0]  # this give the first row of the first channel

tensor([1, 2, 3])

In [106]:
tensor[0][0][0]   # this give the fisrt column value of the first row in first channel

tensor(1)

In [108]:
tensor[:,0] # this give the first row of first channel

tensor([[1, 2, 3]])

In [109]:
tensor[:,:, 1] # this give the all the value of second column

tensor([[2, 5, 8]])

In [110]:
#pytorch have good compatability with numpy array . we can convert the numpy array to tensor or visa versa


import torch
import numpy as np

# converrting array into tensor
array = np.arange(1., 8.,)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [111]:
# since we assign the array into tensor thus any change in array is not efffect the tensor value
array = array+1
tensor, array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([2., 3., 4., 5., 6., 7., 8.]))

In [112]:
# converting the tensor in to array
tensor = torch.ones(7)
array = tensor.numpy()
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [115]:
#since we assign the assign the tensor into array then any change in tensor doesnt impact the array value
tensor = tensor+1
tensor , array

(tensor([4., 4., 4., 4., 4., 4., 4.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [117]:
# reproducibility is important when we want the similar kind of result when we run experiment with random numbers

tensor1 = torch.rand(3,4)
tensor2 = torch.rand(3,4)
tensor1 == tensor2   # this indicate the both tensor are not same 

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [119]:
# Produce the same Tensor
torch.manual_seed(42)
tensor1 = torch.rand(4,5)
torch.manual_seed(42)
tensor2 = torch.rand(4,5)
tensor1==tensor2

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [120]:
! nvidia-smi

Mon Oct 14 14:27:14 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650        Off | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P8               2W /  30W |      6MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [125]:
# check pytorch is using the GPU
import torch
torch.cuda.is_available()

False

In [123]:
# write the device agnostic code which is very helpful for tha code is runing on cpu or GPU

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [126]:
torch.cuda.device_count()

0

In [129]:
# put tensor on gpu 
tensor = torch.tensor([1,2,3]
                      )
tensor , tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [130]:
tensor.numpy()

array([1, 2, 3])

In [132]:
torch.cuda.is_available()

False